name: Push

on:
  push:
    branches:
      - master
    paths:
    - 'dnsconfig.js'
    - 'creds.json'

jobs:
  push:
    name: DNSControl Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl push
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push
